
            case 'SYS_LOGS': return <LogsView currentUser={currentUser} />;
            case 'SYS_BRANCHES': return <BranchesView branches={state.branches || []} onSaveBranch={(b) => api.savePJEntity('branch', b).then(refreshData)} onDeleteBranch={(id) => api.deletePJEntity('branch', id).then(refreshData)} onManageSchedule={(b) => { setEditingBranch(b); setCurrentView('SRV_BRANCH_SCHEDULE'); }} onManageSalesSchedule={(b) => { setEditingBranch(b); setCurrentView('SYS_SALES_SCHEDULE'); }} onViewDetails={(b) => { setEditingBranch(b); setCurrentView('SYS_BRANCH_DETAILS'); }} />;
            case 'SYS_BRANCH_DETAILS': return editingBranch ? <BranchDetailsView branch={editingBranch} state={state} onBack={() => setCurrentView('SYS_BRANCHES')} /> : <Dashboard {...dashboardProps} />;
            case 'SYS_GLOBAL_SCHEDULE': return <GlobalScheduleView state={state} salespeople={state.salespeople} branches={state.branches} schedules={state.salespersonSchedules} onRefresh={refreshData} />;
            case 'SRV_BRANCH_SCHEDULE': return editingBranch ? <BranchScheduleView branch={editingBranch} appointments={state.serviceAppointments || []} clients={state.serviceClients || []} onSaveAppointment={(a) => api.saveAppointment(a as ServiceAppointment).then(refreshData)} onDeleteAppointment={(id) => api.deleteAppointment(id).then(refreshData)} onBack={() => setCurrentView('SYS_BRANCHES')} /> : <Dashboard {...dashboardProps} />;
            case 'SYS_SALES_SCHEDULE': return editingBranch ? <SalespersonScheduleView branch={editingBranch} schedules={state.salespersonSchedules || []} salespeople={state.salespeople || []} onSaveSchedule={(s) => api.saveSalespersonSchedule(s).then(refreshData)} onDeleteSchedule={(id) => api.deleteSalespersonSchedule(id).then(refreshData)} onBack={() => setCurrentView('SYS_BRANCHES')} /> : <Dashboard {...dashboardProps} />;
            case 'OPTICAL_RX': return <OpticalModule opticalRxs={state.opticalRxs || []} contacts={state.contacts || []} laboratories={state.laboratories || []} branches={state.branches || []} onAddRx={() => { setEditingRx(null); setCurrentView('OPTICAL_RX_EDITOR'); }} onEditRx={(rx) => { setEditingRx(rx); setCurrentView('OPTICAL_RX_EDITOR'); }} onDeleteRx={(id) => api.deleteOpticalRx(id).then(refreshData)} onUpdateRx={(rx) => api.saveOpticalRx(rx).then(refreshData)} onStartSaleFromRx={handleStartSaleFromRx} />;
            case 'OPTICAL_RX_EDITOR': return <OpticalRxEditor contacts={state.contacts || []} laboratories={state.laboratories || []} branches={state.branches || []} initialData={editingRx} onSave={(rx) => api.saveOpticalRx(rx).then(() => { refreshData(); setCurrentView('OPTICAL_RX'); })} onCancel={() => setCurrentView('OPTICAL_RX')} />;
            case 'OPTICAL_LABS_MGMT': return <LabsView laboratories={state.laboratories || []} onSaveLaboratory={(l) => api.saveLaboratory(l).then(refreshData)} onDeleteLaboratory={(id) => api.deleteLaboratory(id).then(refreshData)} onViewDetails={(l) => { setEditingLab(l); setCurrentView('OPTICAL_LAB_DETAILS'); }} />;
            case 'OPTICAL_LAB_DETAILS': return editingLab ? <LabDetailsView lab={editingLab} opticalRxs={state.opticalRxs || []} onBack={() => setCurrentView('OPTICAL_LABS_MGMT')} onUpdateRx={(rx) => api.saveOpticalRx(rx).then(refreshData)} /> : <Dashboard {...dashboardProps} />;
            case 'SYS_SALESPEOPLE': return <SalespeopleView salespeople={state.salespeople || []} branches={state.branches || []} members={members || []} commercialOrders={state.commercialOrders || []} onSaveSalesperson={(s) => api.saveLocallyAndQueue('salespeople', s).then(refreshData)} onDeleteSalesperson={(id) => api.deleteLocallyAndQueue('salespeople', id).then(refreshData)} />;
            case 'SYS_SETTINGS': return <SettingsView user={currentUser} pjData={{ companyProfile: state.companyProfile, branches: state.branches || [], costCenters: state.costCenters || [], departments: state.departments || [], projects: state.projects || [], accounts: state.accounts || [] }} onUpdateSettings={(s) => updateSettings(s).then(() => checkAuth())} onOpenCollab={() => {}} onSavePJEntity={(t, d) => api.savePJEntity(t, d).then(refreshData)} onDeletePJEntity={(t, id) => api.deletePJEntity(t, id).then(refreshData)} />;
            case 'SYS_HELP': return <HelpCenter activeModules={currentUser.settings?.activeModules} />;
